[project]
name = "mcp-calculator"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "DaniAThaheem", email = "danimsbzuacc@outlook.com" }
]
requires-python = ">=3.13"
dependencies = [
    "fastmcp>=2.3.0,<3",
    "mcp>=1,<2",
    "uvicorn>=0.34.0",
]

[project.scripts]
mcp = "Remote_Server.server:main"

[build-system]
requires = ["uv_build>=0.12.21,<0.13.0"]
build-backend = "uv_build"

[tool.uv.build-backend]
module-name = "Remote_Server"
